/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.RegisterRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-03T10:32:36.707Z[GMT]")
@Api(value = "logout", description = "the logout API")
public interface LogoutApi {

    @ApiOperation(value = "Logs the user out of the system", nickname = "logoutUser", notes = "Logs out user en removes authtoken from active tokens", authorizations = {
        @Authorization(value = "ApiKeyAuth")    }, tags={ "Authentication","Customer operation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "You have succesfully logged out."),
        @ApiResponse(code = 400, message = "Something went wrong with logging out, please try again."),
        @ApiResponse(code = 401, message = "Unauthorized."),
        @ApiResponse(code = 403, message = "Forbidden."),
        @ApiResponse(code = 404, message = "The page that you are trying to enter does not exist anymore."),
        @ApiResponse(code = 406, message = "Something went wrong with your credentials, please try again."),
        @ApiResponse(code = 429, message = "You have clicked too many times on the log out button, please wait a minute before you try again.") })
    @RequestMapping(value = "/logout",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> logoutUser();

}
